### ISSUE TITLE
Bugged model after importing certain sco files

### ISSUE THREAD

**Issue by Titukis** [space928/Blender-O3D-IO-Public#71]
No idea why this happens but when import certain sco files (for example from Sceneryobjects\Kreuz_MC folder) it shows nothing like it has to be. How can I fix this? 
![image](https://github.com/space928/Blender-O3D-IO-Public/assets/96497869/71bba8d9-e1e8-40ea-96b6-712c8c254d8d)

**Comment by space928** [comment]
Many of the o3d files which come with the game are encrypted. You can tell by looking at the first few bytes of the file, if the highlighted bytes are not `0xffffffff` then the file is encrypted:
![image](https://github.com/space928/Blender-O3D-IO-Public/assets/15130114/a8857c72-648f-41fd-8bcd-aadb61ac6afa)

For legal reasons I've chosen not to publish the o3d decryption code and as such when you try to import an encrypted model the vertices will be wrong (the encryption has the effect of scrambling the vertices).

I'm closing this issue as this is intentional behaviour.

**Comment by Titukis** [comment]
so there is no way to get those objects? Is there any alternative Scenery Object pack I can download (with same looking objects)?

**Comment by space928** [comment]
No, decrypting encrypted o3d files would be defeating the DRM. You can always look on WebDisk for alternative models, but I'm afraid I can't help you any further.
